global:
  scrape_interval: 10s  # how often to scrape metrics

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "custom_exporter_openweather"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # Windows Docker: host machine exporter
